from pathlib import Path

script = r'''[CmdletBinding()]
param(
    [string]$Repo = "$HOME\openclaw",
    [string]$FsSafeLocal = "$HOME\fs-safe",
    [string]$CodexLocal = "$HOME\codex-0.146.1\codex-cli",
    [switch]$SkipPull,
    [switch]$ReinstallGateway
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Invoke-Checked {
    param(
        [Parameter(Mandatory)][string]$FilePath,
        [Parameter()][string[]]$ArgumentList = @()
    )

    Write-Host "`n> $FilePath $($ArgumentList -join ' ')" -ForegroundColor Cyan
    & $FilePath @ArgumentList
    if ($LASTEXITCODE -ne 0) {
        throw "$FilePath failed with exit code $LASTEXITCODE"
    }
}

function Get-PackageVersion {
    param([Parameter(Mandatory)][string]$PackageDir)

    $packageJson = Join-Path $PackageDir "package.json"
    if (-not (Test-Path $packageJson)) {
        throw "package.json not found: $packageJson"
    }

    return (Get-Content $packageJson -Raw | ConvertFrom-Json).version
}

function Set-YamlOverride {
    param(
        [Parameter(Mandatory)][string]$Text,
        [Parameter(Mandatory)][string]$Key,
        [Parameter(Mandatory)][string]$Value
    )

    $escapedKey = [regex]::Escape($Key)
    $pattern = "(?m)^(\s*)`"$escapedKey`":\s*.+$"
    $match = [regex]::Match($Text, $pattern)

    if ($match.Success) {
        $indent = $match.Groups[1].Value
        $replacement = "${indent}`"$Key`": `"$Value`""
        return $Text.Remove($match.Index, $match.Length).Insert($match.Index, $replacement)
    }

    $overrides = [regex]::Match($Text, "(?m)^overrides:\s*$")
    if (-not $overrides.Success) {
        throw "Could not find root 'overrides:' section in pnpm-workspace.yaml"
    }

    $line = "`n  `"$Key`": `"$Value`""
    return $Text.Insert($overrides.Index + $overrides.Length, $line)
}

# ---- Validate tools and paths ------------------------------------------------

foreach ($cmd in @("git", "node", "pnpm")) {
    if (-not (Get-Command $cmd -ErrorAction SilentlyContinue)) {
        throw "Required command not found on PATH: $cmd"
    }
}

if (-not (Test-Path $Repo))       { throw "OpenClaw repo not found: $Repo" }
if (-not (Test-Path $FsSafeLocal)){ throw "fs-safe checkout not found: $FsSafeLocal" }
if (-not (Test-Path $CodexLocal)) { throw "Codex local package not found: $CodexLocal" }

$Repo = (Resolve-Path $Repo).Path
$FsSafeLocal = (Resolve-Path $FsSafeLocal).Path
$CodexLocal = (Resolve-Path $CodexLocal).Path

Push-Location $Repo
try {
    Invoke-Checked git @("rev-parse", "--is-inside-work-tree")

    # These are the only tracked files this workaround intentionally changes.
    $managedFiles = @(
        "package.json",          # may be dirty from the initial pnpm add -w workaround
        "pnpm-workspace.yaml",   # local dependency overrides
        "pnpm-lock.yaml"         # regenerated by pnpm install
    )

    # Refuse to overwrite unrelated OpenClaw source changes.
    $changed = @(& git diff --name-only HEAD)
    if ($LASTEXITCODE -ne 0) { throw "git diff failed" }

    $unexpected = @($changed | Where-Object { $_ -and ($_ -notin $managedFiles) })
    if ($unexpected.Count -gt 0) {
        throw "Unrelated tracked changes detected. Commit/stash them first:`n  $($unexpected -join "`n  ")"
    }

    # Back up our current workaround diff before restoring upstream copies.
    $backupRoot = Join-Path $HOME ".openclaw-update-backups"
    New-Item -ItemType Directory -Force -Path $backupRoot | Out-Null
    $stamp = Get-Date -Format "yyyyMMdd-HHmmss"
    $backup = Join-Path $backupRoot "openclaw-local-overrides-$stamp.patch"

    $diff = & git diff -- $managedFiles
    if ($LASTEXITCODE -ne 0) { throw "git diff backup failed" }
    if ($diff) {
        $diff | Set-Content -Encoding utf8 $backup
        Write-Host "Saved local workaround diff: $backup" -ForegroundColor DarkGray
    }

    # Restore only files managed by this script, leaving other files untouched.
    Invoke-Checked git (@("restore", "--") + $managedFiles)

    if (-not $SkipPull) {
        Invoke-Checked git @("pull", "--ff-only")
    }

    # ---- Detect versions required by the newly updated OpenClaw tree ----------

    $rootPackage = Get-Content (Join-Path $Repo "package.json") -Raw | ConvertFrom-Json
    $codexPackage = Get-Content (Join-Path $Repo "extensions\codex\package.json") -Raw | ConvertFrom-Json

    $requiredCodex = $codexPackage.dependencies.'@openai/codex'
    if (-not $requiredCodex) {
        throw "Could not determine required @openai/codex version."
    }

    $workspacePath = Join-Path $Repo "pnpm-workspace.yaml"
    $workspaceText = Get-Content $workspacePath -Raw

    $requiredFsSafe = $null
    if ($rootPackage.dependencies -and
        $rootPackage.dependencies.PSObject.Properties.Name -contains '@openclaw/fs-safe') {
        $requiredFsSafe = $rootPackage.dependencies.'@openclaw/fs-safe'
    }

    if (-not $requiredFsSafe) {
        $m = [regex]::Match($workspaceText, '"@openclaw/fs-safe@([^"]+)"')
        if ($m.Success) {
            $requiredFsSafe = $m.Groups[1].Value
        }
    }

    if (-not $requiredFsSafe) {
        throw "Could not determine required @openclaw/fs-safe version."
    }

    $localCodex = Get-PackageVersion $CodexLocal
    $localFsSafe = Get-PackageVersion $FsSafeLocal

    Write-Host "`nRequired/local dependency versions:" -ForegroundColor Green
    Write-Host "  Codex:   required $requiredCodex ; local $localCodex"
    Write-Host "  fs-safe: required $requiredFsSafe ; local $localFsSafe"

    if ($localCodex -ne $requiredCodex) {
        throw @"
OpenClaw now requires @openai/codex $requiredCodex, but the local package is $localCodex.
Create/update the matching local Codex checkout, then rerun with:
  -CodexLocal <path-to-codex-cli-$requiredCodex>
"@
    }

    if ($localFsSafe -ne $requiredFsSafe) {
        throw @"
OpenClaw now requires @openclaw/fs-safe $requiredFsSafe, but the local checkout is $localFsSafe.
Update/checkout fs-safe $requiredFsSafe, build it, then rerun.
"@
    }

    # ---- Reapply corporate-registry workarounds -------------------------------

    $fsRelative = [IO.Path]::GetRelativePath($Repo, $FsSafeLocal).Replace('\', '/')
    $codexRelative = [IO.Path]::GetRelativePath($Repo, $CodexLocal).Replace('\', '/')

    $fsSpec = "file:$fsRelative"
    $codexSpec = "file:$codexRelative"

    # Generic overrides handle direct/transitive requests.
    $workspaceText = Set-YamlOverride $workspaceText "@openclaw/fs-safe" $fsSpec
    $workspaceText = Set-YamlOverride $workspaceText "@openai/codex" $codexSpec

    # OpenClaw currently has a more-specific codex-acp override; it wins over
    # the generic rule unless we redirect it locally as well.
    $specificPattern = '(?m)^(\s*)("@agentclientprotocol/codex-acp@[^"]+>@openai/codex"):\s*.+$'
    $specific = [regex]::Match($workspaceText, $specificPattern)

    if ($specific.Success) {
        $indent = $specific.Groups[1].Value
        $key = $specific.Groups[2].Value
        $replacement = "${indent}${key}: `"$codexSpec`""
        $workspaceText = $workspaceText.Remove($specific.Index, $specific.Length).
            Insert($specific.Index, $replacement)
    }

    [IO.File]::WriteAllText(
        $workspacePath,
        $workspaceText,
        [Text.UTF8Encoding]::new($false)
    )

    Write-Host "`nApplied local dependency overrides:" -ForegroundColor Green
    Write-Host "  @openclaw/fs-safe -> $fsSpec"
    Write-Host "  @openai/codex     -> $codexSpec"

    # ---- Install, build, link, restart ----------------------------------------

    Invoke-Checked pnpm @("install", "--force")
    Invoke-Checked pnpm @("build")
    Invoke-Checked pnpm @("ui:build")
    Invoke-Checked pnpm @("link", "--global")

    Write-Host "`nGit checkout CLI:" -ForegroundColor Green
    Invoke-Checked pnpm @("openclaw", "--version")

    if ($ReinstallGateway) {
        Invoke-Checked pnpm @("openclaw", "gateway", "install", "--force")
    } else {
        Invoke-Checked pnpm @("openclaw", "gateway", "restart")
    }

    Invoke-Checked pnpm @("openclaw", "gateway", "status")

    Write-Host "`nUpdate complete." -ForegroundColor Green
    Write-Host "Expected dirty files after the update:"
    Invoke-Checked git @("status", "--short")
}
finally {
    Pop-Location
}
'''

path = Path("/mnt/data/Update-OpenClawCorporate.ps1")
path.write_text(script, encoding="utf-8")
print(path)
